// <auto-generated />
using System;
using Bean_Scene_Reservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bean_Scene_Reservation.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529133048_AddSittingTypeModel")]
    partial class AddSittingTypeModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bean_Scene_Reservation.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Outside"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("Bean_Scene_Reservation.Models.SittingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SittingTypes");
                });

            modelBuilder.Entity("Bean_Scene_Reservation.Models.Table", b =>
                {
                    b.Property<string>("TableNumber")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.HasKey("TableNumber");

                    b.HasIndex("AreaId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableNumber = "M1",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M2",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M3",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M4",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M5",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M6",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M7",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M8",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M9",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "M10",
                            AreaId = 1
                        },
                        new
                        {
                            TableNumber = "O1",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O2",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O3",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O4",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O5",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O6",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O7",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O8",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O9",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "O10",
                            AreaId = 2
                        },
                        new
                        {
                            TableNumber = "B1",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B2",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B3",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B4",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B5",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B6",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B7",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B8",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B9",
                            AreaId = 3
                        },
                        new
                        {
                            TableNumber = "B10",
                            AreaId = 3
                        });
                });

            modelBuilder.Entity("Bean_Scene_Reservation.Models.Timeslot", b =>
                {
                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Time");

                    b.ToTable("Timeslots");

                    b.HasData(
                        new
                        {
                            Time = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(13, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(14, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(18, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(19, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(20, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(20, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(21, 30, 0)
                        },
                        new
                        {
                            Time = new TimeOnly(22, 0, 0)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bean_Scene_Reservation.Models.Table", b =>
                {
                    b.HasOne("Bean_Scene_Reservation.Models.Area", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bean_Scene_Reservation.Models.Area", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
